//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CEPT.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CEPT_DIALOG                 102
#define IDR_MAINFRAME                   128
#define IDC_H                           1000
#define IDC_He                          1001
#define IDC_NUM                         1002
#define IDC_ENNAME                      1003
#define IDC_CNNAME                      1004
#define IDC_SYMBOL                      1005
#define IDC_Li                          1006
#define IDC_WEIGHT                      1007
#define IDC_ELECTRON                    1008
#define IDC_MPOINT                      1009
#define IDC_BPOINT                      1010
#define IDC_Be                          1011
#define IDC_B                           1012
#define IDC_C                           1013
#define IDC_N                           1014
#define IDC_O                           1015
#define IDC_F                           1016
#define IDC_Ne                          1017
#define IDC_Na                          1018
#define IDC_Mg                          1019
#define IDC_Al                          1020
#define IDC_Si                          1021
#define IDC_P                           1022
#define IDC_S                           1023
#define IDC_Cl                          1024
#define IDC_Ar                          1025
#define IDC_K                           1027
#define IDC_Ca                          1028
#define IDC_Sc                          1029
#define IDC_Ti                          1030
#define IDC_V                           1031
#define IDC_Cr                          1032
#define IDC_Mn                          1033
#define IDC_Fe                          1034
#define IDC_Co                          1035
#define IDC_Ni                          1036
#define IDC_Cu                          1037
#define IDC_Zn                          1038
#define IDC_PINYIN                      1040
#define IDC_Ga                          1041
#define IDC_Ge                          1042
#define IDC_As                          1043
#define IDC_Se                          1044
#define IDC_Br                          1045
#define IDC_Kr                          1046
#define IDC_Rb                          1047
#define IDC_Sr                          1048
#define IDC_Y                           1049
#define IDC_Zr                          1050
#define IDC_Nb                          1051
#define IDC_Mo                          1052
#define IDC_Tc                          1053
#define IDC_Ru                          1054
#define IDC_Rh                          1055
#define IDC_Pd                          1056
#define IDC_Ag                          1057
#define IDC_Cd                          1058
#define IDC_In                          1059
#define IDC_Sn                          1060
#define IDC_Sb                          1061
#define IDC_Te                          1062
#define IDC_I                           1063
#define IDC_Xe                          1064
#define IDC_Cs                          1065
#define IDC_Ba                          1066
#define IDC_La                          1067
#define IDC_Hf                          1068
#define IDC_Ta                          1069
#define IDC_W                           1070
#define IDC_Re                          1071
#define IDC_Os                          1072
#define IDC_Ir                          1073
#define IDC_Pt                          1074
#define IDC_Au                          1075
#define IDC_Hg                          1076
#define IDC_Tl                          1077
#define IDC_Pb                          1078
#define IDC_Bi                          1079
#define IDC_Po                          1080
#define IDC_At                          1081
#define IDC_Rn                          1082
#define IDC_Fr                          1083
#define IDC_Ra                          1084
#define IDC_Ac                          1085
#define IDC_Rf                          1086
#define IDC_Db                          1087
#define IDC_Sg                          1088
#define IDC_Bh                          1089
#define IDC_Hs                          1090
#define IDC_Mt                          1091
#define IDC_Uun                         1094
#define IDC_Uuu                         1095
#define IDC_Uub                         1096
#define IDC_Uut                         1097
#define IDC_Uuq                         1098
#define IDC_Ac2                         1101
#define IDC_Ce                          1102
#define IDC_Pr                          1103
#define IDC_Nd                          1104
#define IDC_Pm                          1105
#define IDC_Sm                          1106
#define IDC_Eu                          1107
#define IDC_Gd                          1108
#define IDC_Tb                          1109
#define IDC_Dy                          1110
#define IDC_Ho                          1111
#define IDC_Er                          1112
#define IDC_Tm                          1113
#define IDC_Yb                          1114
#define IDC_Lu                          1115
#define IDC_La2                         1116
#define IDC_Th                          1117
#define IDC_Pa                          1118
#define IDC_U                           1119
#define IDC_Np                          1120
#define IDC_Pu                          1121
#define IDC_Am                          1122
#define IDC_Cm                          1123
#define IDC_Bk                          1124
#define IDC_Cf                          1125
#define IDC_Es                          1126
#define IDC_Fm                          1127
#define IDC_Md                          1128
#define IDC_No                          1129
#define IDC_Lr                          1130
#define IDC_Uup                         1131
#define IDC_Uuh                         1132
#define IDC_Uus                         1133
#define IDC_Uuo                         1134

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        129
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1027
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
